# -*- coding: utf-8 -*-
"""long_responses.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CiXeS2nigxtLZzPsPjyARbH_fe5pWIUr
"""

import random

R_EATING = "I can not complaint anything because I'm a bot obviously!"
R_ADVICE = "If I were you, I would go to the internet and type exactly what you wrote there!"

def unknown():
    response = ["Could you please re-phrase that? ",
                "...",
                "Not Found any details",
                "What does that mean?"][
        random.randrange(4)]
    return response